### ISSUE TITLE
Terrain does not load after entering the Nether

### ISSUE THREAD

**Issue by kostek001** [QuiltMC/quilted-fabric-api#109]
After entering the Nether in the first world, then leaving and joining the second world (with never generated Nether), entering the Nether results in no terrain loading. After leaving and joining the second world, the structures that were supposed to be generated within render distance are not.

OS: Linux
Java: 17.0.7
Minecraft: 1.20.1
Quilt Loader: 0.19.2
Quilted Fabric API: 7.0.6

Steps to reproduce:
1. Create new world
2. Enter the nether (it loads normally)
3. Leave world
4. Create second new world
5. Enter the nether
6. Terrain not loading, and log spams with:
```
[Render thread/ERROR]: Error executing task on Client
java.lang.IllegalArgumentException: No value with id -1
	at net.minecraft.class_2359.method_39974(class_2359.java:19) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2834.method_12289(class_2834.java:82) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2841.method_12326(class_2841.java:174) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2826.method_12258(class_2826.java:159) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2818.method_12224(class_2818.java:456) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_631.method_16020(class_631.java:117) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_634.method_38539(class_634.java:773) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_634.method_11128(class_634.java:738) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2672.method_11528(class_2672.java:45) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2672.method_11054(class_2672.java:12) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.19.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

Full crash log: https://mclo.gs/Q6ybvpK

**Comment by rinOfTheStars** [comment]
Is actually a bug in QSL, and should be closed here as a result. Going to open an issue on QSL for this momentarily.

**Comment by rinOfTheStars** [comment]
should be fixed in https://github.com/QuiltMC/quilt-standard-libraries/pull/333

**Comment by EnnuiL** [comment]
...not! It turns out we had 2 usable different approaches to injecting modded nether biomes to the game, and the older one, now that there are no obstacles on its way, turned out to be the least complex and possibly lighter approach;
Next QSL and QFAPI updates will have this issue fixed!
