### ISSUE TITLE
Quilted Fabric API (QFAPI) and Quilt Standard Libraries (QSL) Crash

### ISSUE THREAD

**Issue by justjosh104326** [QuiltMC/quilted-fabric-api#174]
When ever I launch Quilt Loader version 0.26.3 or above with Quilted Fabric version [1.21] QFAPI 11.0.0-alpha.3 and QSL 10.0.0-alpha.1 it crashes with the message:
---- Crashed! ----
Date/Time: 2024/11/19 18:36:40.4681 [+0000]
Quilt Loader Version: 0.27.0

-- Crash --

org.quiltmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:559)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:504)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:302)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:190)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:176)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.client.main.Main.main(Main.java:219)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:499)
	... 11 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#quilted_fabric_screen_api_v1:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod quilted_fabric_screen_api_v1] from phase [DEFAULT] in config [#quilted_fabric_screen_api_v1:fabric-screen-api-v1.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on beforeScreenTick could not find any targets matching 'Lnet/minecraft/class_310;method_1572()V' in net/minecraft/class_310. Using refmap client-quilted_fabric_screen_api_v1-refmap.json [INJECT_PREPARE Applicator Phase -> #quilted_fabric_screen_api_v1:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod quilted_fabric_screen_api_v1 -> Prepare Injections -> handler$zif000$quilted_fabric_screen_api_v1$beforeScreenTick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse ->  -> Validate Targets]
	at org.spongepowered.asm.mixin.injection.selectors.TargetSelectors.validate(TargetSelectors.java:346)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:369)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:340)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:331)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:48)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:196)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:664)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1399)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 14 more

-- Mods --

| Index | Mod                                               | ID                                           | Version                     | Type    | File Hash (SHA-1)                        | File(s)                                                                                                                                        | Sub-File                                                                       |
|------:|---------------------------------------------------|----------------------------------------------|-----------------------------|---------|------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
|     3 | Minecraft                                         | minecraft                                    | 1.21.3                      | Builtin | d024661bbcb08b600032e5bec438971d9ba56707 | <game>\.cache\quilt_loader\remappedJars\minecraft-1.21.3-0.27.0\client-intermediary.jar                                                        | /                                                                              |
|       |                                                   |                                              |                             |         | d024661bbcb08b600032e5bec438971d9ba56707 | <game>\libraries\com\mojang\datafixerupper\8.0.16\datafixerupper-8.0.16.jar                                                                    | /                                                                              |
|       |                                                   |                                              |                             |         | d024661bbcb08b600032e5bec438971d9ba56707 | <game>\libraries\com\mojang\authlib\6.0.55\authlib-6.0.55.jar                                                                                  | /                                                                              |
|       |                                                   |                                              |                             |         |                                          | <game>\libraries\com\mojang\brigadier\1.3.10\brigadier-1.3.10.jar                                                                              | /                                                                              |
|    37 | MixinExtras                                       | mixinextras                                  | 0.4.1                       | Fabric  | 1d975b20ff84c443e7a17ddc1c8c19f9eb15dfb6 | <game>\libraries\org\quiltmc\quilt-loader\0.27.0\quilt-loader-0.27.0.jar                                                                       | /META-INF/jars/mixinextras-fabric-0.4.1.jar                                    |
|    47 | OpenJDK 64-Bit Server VM                          | java                                         | 21                          | Builtin |                                          | <user>\AppData\Local\Packages\Microsoft.4297127D64EC6_8wekyb3d8bbwe\LocalCache\Local\runtime\java-runtime-delta\windows-x64\java-runtime-delta |                                                                                |
|    24 | Quilt Loader                                      | quilt_loader                                 | 0.27.0                      | Quilt   | 1d975b20ff84c443e7a17ddc1c8c19f9eb15dfb6 | <game>\libraries\org\quiltmc\quilt-loader\0.27.0\quilt-loader-0.27.0.jar                                                                       |                                                                                |
|    15 | Quilted Fabric API                                | quilted_fabric_api                           | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      |                                                                                |
|    43 | Quilted Fabric API Base                           | quilted_fabric_api_base                      | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_api_base-11.0.0-alpha.3.jar                      |
|    49 | Quilted Fabric API Lookup API (v1)                | quilted_fabric_api_lookup_api_v1             | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_api_lookup_api_v1-11.0.0-alpha.3.jar             |
|    10 | Quilted Fabric Biome API (v1)                     | quilted_fabric_biome_api_v1                  | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_biome_api_v1-11.0.0-alpha.3.jar                  |
|    45 | Quilted Fabric Block API (v1)                     | quilted_fabric_block_api_v1                  | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_block_api_v1-11.0.0-alpha.3.jar                  |
|    30 | Quilted Fabric BlockRenderLayer Registration (v1) | quilted_fabric_blockrenderlayer_v1           | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_blockrenderlayer_v1-11.0.0-alpha.3.jar           |
|    33 | Quilted Fabric BlockView API (v2)                 | quilted_fabric_block_view_api_v2             | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_block_view_api_v2-11.0.0-alpha.3.jar             |
|    34 | Quilted Fabric Client Tags                        | quilted_fabric_client_tags_api_v1            | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_client_tags_api_v1-11.0.0-alpha.3.jar            |
|    13 | Quilted Fabric Command API (v1)                   | quilted_fabric_command_api_v1                | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_command_api_v1-11.0.0-alpha.3.jar                |
|    38 | Quilted Fabric Command API (v2)                   | quilted_fabric_command_api_v2                | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_command_api_v2-11.0.0-alpha.3.jar                |
|     5 | Quilted Fabric Commands (v0)                      | quilted_fabric_commands_v0                   | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_commands_v0-11.0.0-alpha.3.jar                   |
|    46 | Quilted Fabric Content Registries (v0)            | quilted_fabric_content_registries_v0         | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_content_registries_v0-11.0.0-alpha.3.jar         |
|    48 | Quilted Fabric Convention Tags                    | quilted_fabric_convention_tags_v1            | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_convention_tags_v1-11.0.0-alpha.3.jar            |
|    20 | Quilted Fabric Convention Tags (v2)               | quilted_fabric_convention_tags_v2            | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_convention_tags_v2-11.0.0-alpha.3.jar            |
|    23 | Quilted Fabric Crash Report Info (v1)             | quilted_fabric_crash_report_info_v1          | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_crash_report_info_v1-11.0.0-alpha.3.jar          |
|    51 | Quilted Fabric Data Attachment API (v1)           | quilted_fabric_data_attachment_api_v1        | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_data_attachment_api_v1-11.0.0-alpha.3.jar        |
|    17 | Quilted Fabric Data Generation API (v1)           | quilted_fabric_data_generation_api_v1        | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_data_generation_api_v1-11.0.0-alpha.3.jar        |
|    42 | Quilted Fabric Dimensions API (v1)                | quilted_fabric_dimensions_v1                 | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_dimensions_v1-11.0.0-alpha.3.jar                 |
|     2 | Quilted Fabric Entity Events (v1)                 | quilted_fabric_entity_events_v1              | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_entity_events_v1-11.0.0-alpha.3.jar              |
|    32 | Quilted Fabric Events Interaction (v0)            | quilted_fabric_events_interaction_v0         | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_events_interaction_v0-11.0.0-alpha.3.jar         |
|    14 | Quilted Fabric Game Rule API (v1)                 | quilted_fabric_game_rule_api_v1              | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_game_rule_api_v1-11.0.0-alpha.3.jar              |
|     7 | Quilted Fabric Item API (v1)                      | quilted_fabric_item_api_v1                   | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_item_api_v1-11.0.0-alpha.3.jar                   |
|     4 | Quilted Fabric Item Group API (v1)                | quilted_fabric_item_group_api_v1             | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_item_group_api_v1-11.0.0-alpha.3.jar             |
|    36 | Quilted Fabric Key Binding API (v1)               | quilted_fabric_key_binding_api_v1            | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_key_binding_api_v1-11.0.0-alpha.3.jar            |
|     0 | Quilted Fabric Key Bindings (v0)                  | quilted_fabric_keybindings_v0                | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_keybindings_v0-11.0.0-alpha.3.jar                |
|     9 | Quilted Fabric Lifecycle Events (v1)              | quilted_fabric_lifecycle_events_v1           | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_lifecycle_events_v1-11.0.0-alpha.3.jar           |
|    19 | Quilted Fabric Loot API (v2)                      | quilted_fabric_loot_api_v2                   | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_loot_api_v2-11.0.0-alpha.3.jar                   |
|    18 | Quilted Fabric Loot API (v3)                      | quilted_fabric_loot_api_v3                   | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_loot_api_v3-11.0.0-alpha.3.jar                   |
|    28 | Quilted Fabric Message API (v1)                   | quilted_fabric_message_api_v1                | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_message_api_v1-11.0.0-alpha.3.jar                |
|    39 | Quilted Fabric Model Loading API (v1)             | quilted_fabric_model_loading_api_v1          | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_model_loading_api_v1-11.0.0-alpha.3.jar          |
|     1 | Quilted Fabric Networking API (v1)                | quilted_fabric_networking_api_v1             | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_networking_api_v1-11.0.0-alpha.3.jar             |
|    22 | Quilted Fabric Object Builder API (v1)            | quilted_fabric_object_builder_api_v1         | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_object_builder_api_v1-11.0.0-alpha.3.jar         |
|    12 | Quilted Fabric Particles (v1)                     | quilted_fabric_particles_v1                  | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_particles_v1-11.0.0-alpha.3.jar                  |
|    26 | Quilted Fabric Recipe API (v1)                    | quilted_fabric_recipe_api_v1                 | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_recipe_api_v1-11.0.0-alpha.3.jar                 |
|    44 | Quilted Fabric Registry Sync (v0)                 | quilted_fabric_registry_sync_v0              | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_registry_sync_v0-11.0.0-alpha.3.jar              |
|    40 | Quilted Fabric Renderer - Indigo                  | quilted_fabric_renderer_indigo               | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_renderer_indigo-11.0.0-alpha.3.jar               |
|    16 | Quilted Fabric Renderer API (v1)                  | quilted_fabric_renderer_api_v1               | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_renderer_api_v1-11.0.0-alpha.3.jar               |
|    21 | Quilted Fabric Renderer Registries (v1)           | quilted_fabric_renderer_registries_v1        | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_renderer_registries_v1-11.0.0-alpha.3.jar        |
|    31 | Quilted Fabric Rendering (v0)                     | quilted_fabric_rendering_v0                  | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_rendering_v0-11.0.0-alpha.3.jar                  |
|    50 | Quilted Fabric Rendering (v1)                     | quilted_fabric_rendering_v1                  | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_rendering_v1-11.0.0-alpha.3.jar                  |
|    41 | Quilted Fabric Rendering Data Attachment (v1)     | quilted_fabric_rendering_data_attachment_v1  | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_rendering_data_attachment_v1-11.0.0-alpha.3.jar  |
|     6 | Quilted Fabric Rendering Fluids (v1)              | quilted_fabric_rendering_fluids_v1           | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_rendering_fluids_v1-11.0.0-alpha.3.jar           |
|     8 | Quilted Fabric Resource Conditions API (v1)       | quilted_fabric_resource_conditions_api_v1    | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_resource_conditions_api_v1-11.0.0-alpha.3.jar    |
|    11 | Quilted Fabric Resource Loader (v0)               | quilted_fabric_resource_loader_v0            | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_resource_loader_v0-11.0.0-alpha.3.jar            |
|    27 | Quilted Fabric Screen API (v1)                    | quilted_fabric_screen_api_v1                 | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_screen_api_v1-11.0.0-alpha.3.jar                 |
|    29 | Quilted Fabric Screen Handler API (v1)            | quilted_fabric_screen_handler_api_v1         | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_screen_handler_api_v1-11.0.0-alpha.3.jar         |
|    52 | Quilted Fabric Sound API (v1)                     | quilted_fabric_sound_api_v1                  | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_sound_api_v1-11.0.0-alpha.3.jar                  |
|    25 | Quilted Fabric Transfer API (v1)                  | quilted_fabric_transfer_api_v1               | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_transfer_api_v1-11.0.0-alpha.3.jar               |
|    35 | Quilted Fabric Transitive Access Wideners (v1)    | quilted_fabric_transitive_access_wideners_v1 | 11.0.0-alpha.3+0.102.0-1.21 | Quilt   | 4e10dd46af8620a257af7b8130de69a53e1c791d | <mods>\quilted-fabric-api-11.0.0-alpha.3+0.102.0-1.21.jar                                                                                      | /META-INF/jars/quilted_fabric_transitive_access_wideners_v1-11.0.0-alpha.3.jar |
|------:|---------------------------------------------------|----------------------------------------------|-----------------------------|---------|------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
Mod Table Version: 2
Plugin Types: {quilted_fabric_loader=[Fabric], quilt_loader=[Quilt, Builtin]}

---- end of report ----

the minecraft launcher then has the exit code 1. I have no other mods installed.

**Comment by ChilliadEmerald** [comment]
Hey, I had this issue too but after looking around on the discord server, I found that this crash is caused by QFAPI not having any versions for anything higher than 1.21.1 yet. The only fix will be to wait for the newer versions of QFAPI to release.
