### ISSUE TITLE
BCLib 2.0.5 on Quilted Fabric: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.biome.TheEndBiomeData

### ISSUE THREAD

**Issue by lospejos** [QuiltMC/quilted-fabric-api#24]
When running `BCLib` version `2.0.5` on  `Minecraft` version `1.19` with `Quilted Fabric Api` version `qfapi-2.0.0-beta.1_qsl-2.0.0-beta.8_fapi-0.56.3_mc-1.19` I get error:
```
[12:59:11] [main/ERROR]: Minecraft has crashed!
org.quiltmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/biome/TheEndBiomeData
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:425) ~[quilt-loader-0.17.1-beta.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.1-beta.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.1-beta.4.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/biome/TheEndBiomeData
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.getBiomes(BCLibEndBiomeSource.java:204) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.<init>(BCLibEndBiomeSource.java:82) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.<init>(BCLibEndBiomeSource.java:78) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.api.v2.levelgen.LevelGenUtil.getBCLEndLevelStem(LevelGenUtil.java:80) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.createEndStem(BCLWorldPresetSettings.java:107) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.buildDimensionMap(BCLWorldPresetSettings.java:85) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.buildPreset(BCLWorldPresetSettings.java:71) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresets.lambda$static$1(BCLWorldPresets.java:43) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresets.bootstrapPresets(BCLWorldPresets.java:101) ~[bclib-2.0.5.jar:?]
	at net.minecraft.world.gen.WorldPresets$Registrar.modify$dbj000$bcl_getOverworldStem(WorldPresets:571) ~[?:?]
	at net.minecraft.world.gen.WorldPresets$Registrar.initAndGetDefault(WorldPresets:90) ~[?:?]
	at net.minecraft.world.gen.WorldPresets.initAndGetDefault(WorldPresets:107) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:154) ~[minecraft-1.19-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) ~[quilt-loader-0.17.1-beta.4.jar:?]
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.biome.TheEndBiomeData
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:159) ~[quilt-loader-0.17.1-beta.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.getBiomes(BCLibEndBiomeSource.java:204) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.<init>(BCLibEndBiomeSource.java:82) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.<init>(BCLibEndBiomeSource.java:78) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.api.v2.levelgen.LevelGenUtil.getBCLEndLevelStem(LevelGenUtil.java:80) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.createEndStem(BCLWorldPresetSettings.java:107) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.buildDimensionMap(BCLWorldPresetSettings.java:85) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.buildPreset(BCLWorldPresetSettings.java:71) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresets.lambda$static$1(BCLWorldPresets.java:43) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresets.bootstrapPresets(BCLWorldPresets.java:101) ~[bclib-2.0.5.jar:?]
	at net.minecraft.world.gen.WorldPresets$Registrar.modify$dbj000$bcl_getOverworldStem(WorldPresets:571) ~[?:?]
	at net.minecraft.world.gen.WorldPresets$Registrar.initAndGetDefault(WorldPresets:90) ~[?:?]
	at net.minecraft.world.gen.WorldPresets.initAndGetDefault(WorldPresets:107) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:154) ~[minecraft-1.19-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) ~[quilt-loader-0.17.1-beta.4.jar:?]
	... 9 more
```

I'm not sure is it a Quilt / Quilted Fabric API issue or BCLib mod issue.

Please assist if you can.

Thanks.

**Comment by triphora** [comment]
This isn't something we can reasonably support. BCLib is depending on internal implementation details when it shouldn't be - and this isn't the first instance of this happening either. For more info please see [the forum](https://forum.quiltmc.org/t/mod-incompatibility-megathread/261).

**Comment by lospejos** [comment]
OK, this is the issue in BCLib repo: https://github.com/quiqueck/BCLib/issues/2
Thanks for your support!
