### ISSUE TITLE
Error using Ferrite Core mod: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: unknown:private/malte0811/ferritecore/impl/deduplicator$1

### ISSUE THREAD

**Issue by lospejos** [QuiltMC/quilted-fabric-api#28]
Installed mods:
```
qfapi-4.0.0-beta.4_qsl-3.0.0-beta.7_fapi-0.58.5_mc-1.19.1
architectury-6.0.35-fabric
cloth-config-8.0.75-fabric
modmenu-4.0.5
notenoughcrashes-4.1.6+1.19-fabric
RoughlyEnoughItems-9.1.520
ferritecore-5.0.0-fabric
```

Got error on starting:

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2022-08-05 15:28:25
Description: Initializing game

net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: unknown:private/malte0811/ferritecore/impl/deduplicator$1
	at Not Enough Crashes deobfuscated stack trace.(1.19.1+build.4)
	at net.minecraft.util.Identifier.<init>(Identifier:41)
	at net.minecraft.util.Identifier.<init>(Identifier:50)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.sort(ResourceLoaderImpl.java:184)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.sort(ResourceLoaderImpl.java:107)
	at net.minecraft.resource.ReloadableResourceManagerImpl.handler$zdn000$reload(ReloadableResourceManagerImpl:559)
	at net.minecraft.resource.ReloadableResourceManagerImpl.reload(ReloadableResourceManagerImpl:47)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:647)
	at net.minecraft.client.main.Main.main(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

```

It looks like that it's rather a `Quilted Fabric API`  mod issue than `Ferrite Core` mod issue, because I've also tested it using these mods list:
```
fabric-api-0.58.5+1.19.1
ferritecore-5.0.0-fabric
modmenu-4.0.5
```
e.g. pure `Fabric API` instead of `Quilted Fabric API` and it works fine.

Please assist.

Thanks.

P.S. Also created related bug in `Ferrite Core` project here:  https://github.com/malte0811/FerriteCore/issues/87#issue-1329880937

**Comment by lospejos** [comment]
Tested with the recent `qfapi-4.0.0-beta.5_qsl-3.0.0-beta.9_fapi-0.58.5_mc-1.19.1` mod, error is gone, everything works fine.
Closing this issue.
