### ISSUE TITLE
Crash rendering falling block

### ISSUE THREAD

**Issue by BogTheMudWing** [QuiltMC/quilted-fabric-api#32]
Any falling block within render distance crashes the game.
Minecraft version: 1.19 (viafabric to 1.18.2 server)
Quilt version: 0.17.4
QFAPI/QSL versions: 4.0.0-beta.9 / 3.0.0-beta.14

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 8/23/22, 9:09 AM
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zck000$beforeRenderModel(class_901.java:518)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zck000$beforeRenderModel(class_901.java:518)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Entity being rendered --
Details:
	Entity Type: minecraft:falling_block (net.minecraft.class_1540)
	Entity ID: 57831495
	Entity Name: Falling Block
	Entity's Exact location: 1000532.50, 32.96, 251028.50
	Entity's Block location: World: (1000532,32,251028), Section: (at 4,0,4 in 62533,2,15689; chunk contains blocks 1000528,-64,251024 to 1000543,319,251039), Region: (1954,490; contains chunks 62528,15680 to 62559,15711, blocks 1000448,-64,250880 to 1000959,319,251391)
	Entity's Momentum: 0.00, -0.04, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Immitating BlockState: Block{minecraft:sand}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_901@6b1224f0
	Location: -0.80,3.38,0.16 - World: (-1,3,0), Section: (at 15,3,0 in -1,0,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Rotation: 0.0
	Delta: 0.060004234
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)

-- Affected level --
Details:
	All players: 1 total; [class_746['BogTheMudWing'/57831068, l='ClientLevel', x=1000533.30, y=28.00, z=251028.34]]
	Chunk stats: 1024, 109 F: 0 L: 0 U: 1
	Level dimension: minecraft:overworld
	Level spawn location: World: (2922,84,1324), Section: (at 10,4,12 in 182,5,82; chunk contains blocks 2912,-64,1312 to 2927,319,1327), Region: (5,2; contains chunks 160,64 to 191,95, blocks 2560,-64,1024 to 3071,319,1535)
	Level time: 115135 game time, 562194014 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, continuity/default, continuity/glass_pane_culling_fix, Dragonspeak-1.19-vS1.8

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 390200432 bytes (372 MiB) / 905969664 bytes (864 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12600K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Graphics card #1 name: Intel(R) UHD Graphics 770
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x4680
	Graphics card #1 versionInfo: DriverVersion=31.0.101.3222
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29469.64
	Virtual memory used (MB): 15865.09
	Swap memory total (MB): 13312.00
	Swap memory used (MB): 240.49
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Loaded Shaderpack: (off)
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		architectury: Architectury 5.7.28
		betterf3: BetterF3 1.3.1
		bobby: Bobby 4.0.0
		borderlessmining: Borderless Mining 1.1.4+1.19
		citresewn: CIT Resewn 1.1.1+1.19
		citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.19
		cloth-api: Cloth API 4.0.65
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-client-events-v0: Cloth Client Events v0 4.0.65
		cloth-common-events-v1: Cloth Common Events v1 4.0.65
		cloth-config: Cloth Config v6 7.0.72
		cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
		cloth-utils-v1: Cloth Utils v1 4.0.65
		com_github_llamalad7_mixinextras: MixinExtras 0.0.11
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.2
		continuity: Continuity 2.0.1+1.19
		dynamicfps: Dynamic FPS 2.2.0
		ferritecore: FerriteCore 4.2.1
		fvt: Flour's Various Tweaks 1.11.0-mc1.19
		inspecio: Inspecio 1.4.2+1.19
		io_leangen_geantyref_geantyref: geantyref 1.3.13
		iris: Iris 1.2.6
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		libzoomer: LibZoomer 0.5.0+1.19
		lithium: Lithium 0.8.1
		minecraft: Minecraft 1.19
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 4.0.3
		morechathistory: MoreChatHistory 1.1.0
		nbttooltip: NBT Tooltip 1.7.0
		ok_zoomer: Ok Zoomer 5.0.0-beta.9+1.19
		org_anarres_jcpp: jcpp 1.4.14
		org_codehaus_groovy_groovy: groovy 3.0.11
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.11
		org_joml_joml: joml 1.10.4
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		org_yaml_snakeyaml: snakeyaml 1.30
		phosphor: Phosphor 0.8.1
		pride: Pride Lib 1.1.2+1.19
		quilt_advancement: Quilt Advancement API 2.0.0-beta.16+1.19
		quilt_base: Quilt Base API 2.0.0-beta.16+1.19
		quilt_biome: Quilt Biome API 2.0.0-beta.16+1.19
		quilt_block_entity: Quilt Block Entity API 2.0.0-beta.16+1.19
		quilt_block_extensions: Quilt Block Extensions API 2.0.0-beta.16+1.19
		quilt_client_command: Quilt Client Command API 2.0.0-beta.16+1.19
		quilt_command: Quilt Command API 2.0.0-beta.16+1.19
		quilt_crash_info: Quilt Crash Info 2.0.0-beta.16+1.19
		quilt_dimension: Quilt Dimension API 2.0.0-beta.16+1.19
		quilt_item_content_registry: Quilt Item Content Registry API 2.0.0-beta.16+1.19
		quilt_item_group: Quilt Item Group API 2.0.0-beta.16+1.19
		quilt_item_setting: Quilt Item Setting API 2.0.0-beta.16+1.19
		quilt_lifecycle_events: Quilt Lifecycle Events 2.0.0-beta.16+1.19
		quilt_loader: Quilt Loader 0.17.4
		quilt_networking: Quilt Networking 2.0.0-beta.16+1.19
		quilt_recipe: Quilt Recipe API 2.0.0-beta.16+1.19
		quilt_registry: Quilt Registry API 2.0.0-beta.16+1.19
		quilt_registry_entry_attachments: Quilt Registry Entry Attachments 2.0.0-beta.16+1.19
		quilt_resource_loader: Quilt Resource Loader 2.0.0-beta.16+1.19
		quilt_screen: Quilt Screen API 2.0.0-beta.16+1.19
		quilt_tags: Quilt Tags API 2.0.0-beta.16+1.19
		quilt_tooltip: Quilt Tooltip API 2.0.0-beta.16+1.19
		quilted_fabric_api: Quilted Fabric API 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_api_base: Quilted Fabric API Base 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_api_lookup_api_v1: Quilted Fabric API Lookup API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_biome_api_v1: Quilted Fabric Biome API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_blockrenderlayer_v1: Quilted Fabric BlockRenderLayer Registration (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_command_api_v1: Quilted Fabric Command API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_command_api_v2: Quilted Fabric Command API (v2) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_commands_v0: Quilted Fabric Commands (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_containers_v0: Quilted Fabric Containers (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_content_registries_v0: Quilted Fabric Content Registries (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_convention_tags_api_v1: Quilted Fabric Convention Tags API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_crash_report_info_v1: Quilted Fabric Crash Report Info (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_data_generation_api_v1: Quilted Fabric Data Generation API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_dimensions_v1: Quilted Fabric Dimensions API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_entity_events_v1: Quilted Fabric Entity Events (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_events_interaction_v0: Quilted Fabric Events Interaction (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_events_lifecycle_v0: Quilted Fabric Events Lifecycle (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_game_rule_api_v1: Quilted Fabric Game Rule API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_item_api_v1: Quilted Fabric Item API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_item_groups_v0: Quilted Fabric Item Groups (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_key_binding_api_v1: Quilted Fabric Key Binding API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_keybindings_v0: Quilted Fabric Key Bindings (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_lifecycle_events_v1: Quilted Fabric Lifecycle Events (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_loot_api_v2: Quilted Fabric Loot API (v2) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_loot_tables_v1: Quilted Fabric Loot Tables (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_message_api_v1: Quilted Fabric Message API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_mining_level_api_v1: Quilted Fabric Mining Level API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_models_v0: Quilted Fabric Models (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_networking_api_v1: Quilted Fabric Networking API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_networking_v0: Quilted Fabric Networking (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_object_builder_api_v1: Quilted Fabric Object Builder API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_particles_v1: Quilted Fabric Particles (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_registry_sync_v0: Quilted Fabric Registry Sync (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_renderer_api_v1: Quilted Fabric Renderer API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_renderer_indigo: Quilted Fabric Renderer - Indigo 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_renderer_registries_v1: Quilted Fabric Renderer Registries (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_rendering_data_attachment_v1: Quilted Fabric Rendering Data Attachment (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_rendering_fluids_v1: Quilted Fabric Rendering Fluids (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_rendering_v0: Quilted Fabric Rendering (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_rendering_v1: Quilted Fabric Rendering (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_resource_conditions_api_v1: Quilted Fabric Resource Conditions API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_resource_loader_v0: Quilted Fabric Resource Loader (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_screen_api_v1: Quilted Fabric Screen API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_screen_handler_api_v1: Quilted Fabric Screen Handler API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_textures_v0: Quilted Fabric Textures (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_transfer_api_v1: Quilted Fabric Transfer API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_transitive_access_wideners_v1: Quilted Fabric Transitive Access Wideners (v1) 2.0.0-beta.9+0.58.0-1.19
		slight-gui-modifications: 'Slight' GUI Modifications 2.2.0
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.2+replaymod.rev.bfbc6de
		spruceui: SpruceUI 4.0.0+1.19
		tooltipfix: ToolTip Fix 1.0.5-1.19
		viafabric: ViaFabric 0.4.7+9-main
		viafabric-mc119: ViaFabric for 1.19 0.4.7+9-main
		viaversion: ViaVersion 4.4.0-1.19.1-pre2-SNAPSHOT
		worldeditcui: WorldEditCUI 1.19+01
	Launched Version: quilt-loader-0.17.4-1.19
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, continuity/default, continuity/glass_pane_culling_fix, file/Dragonspeak-1.19-vS1.8 (incompatible)
	Current Language: Dragonspeak (Pyrrhia)
	CPU: 16x 12th Gen Intel(R) Core(TM) i5-12600K
```

**Comment by OroArmor** [comment]
You need the indium mod

**Comment by BogTheMudWing** [comment]
That was so simple...
Thank you so much!
